<?php
/**
 * Template Name: Solar Financing & Rebates Page
 * Description: Dedicated page template for solar loan repayment estimations and incentive lookup.
 *
 * @package Solar_Energy_Child
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();
?>

<main id="primary" class="site-main solar-financing-page">
	<div class="solar-page-banner blue-theme">
		<div class="solar-section-container">
			<h1 class="solar-page-title">Solar Financing & Incentive Calculator</h1>
			<p class="solar-page-lead">Explore 0% down financing options, federal tax credits, and local utility rebates to make your solar transition affordable.</p>
		</div>
	</div>

	<div class="solar-section-container">
		<?php echo do_shortcode( '[solar_financing_calculator]' ); ?>

		<div class="solar-rebates-info-grid">
			<div class="solar-info-card">
				<div class="solar-card-icon">🏛️</div>
				<h3>Federal Clean Energy Tax Credit</h3>
				<p>Claim up to 30% of your total solar system installation cost as a direct credit on your annual federal income taxes.</p>
			</div>
			<div class="solar-info-card">
				<div class="solar-card-icon">💵</div>
				<h3>Net Metering Credits</h3>
				<p>Sell excess solar electricity generated by your roof back to the main power grid for utility bill credits.</p>
			</div>
			<div class="solar-info-card">
				<div class="solar-card-icon">📈</div>
				<h3>Increased Home Equity</h3>
				<p>Solar installations increase property resale value without increasing your local property taxes in most jurisdictions.</p>
			</div>
		</div>
	</div>
</main>

<?php
get_footer();
