<?php
/**
 * Template Name: Solar Financing & Rebates Page
 * Description: Dedicated page template for solar loan repayment estimations and incentive lookup.
 *
 * @package Solar_Energy_Child
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();
?>

<main id="primary" class="site-main solar-financing-page">
	<div class="solar-page-banner blue-theme">
		<div class="solar-section-container">
			<h1 class="solar-page-title">Solar Financing & Incentive Calculator</h1>
			<p class="solar-page-lead">Explore 0% down financing options, federal tax credits, and local utility rebates to make your solar transition affordable.</p>
		</div>
	</div>

	<div class="solar-section-container">
		<?php echo do_shortcode( '[solar_financing_calculator]' ); ?>

		<div class="solar-rebates-info-grid">
			<div class="solar-info-card">
				<div class="solar-card-icon">
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" style="width:24px;height:24px;color:var(--solar-primary);margin:0 auto;"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21v-8.25M15.75 21v-8.25M8.25 21v-8.25M3 9l9-6 9 6m-1.5 12V10.332A48.36 48.36 0 0012 9.75c-2.551 0-5.056.2-7.5.582V21M3 21h18M12 6.75h.008v.008H12V6.75z" /></svg>
				</div>
				<h3>Federal Clean Energy Tax Credit</h3>
				<p>Claim up to 30% of your total solar system installation cost as a direct credit on your annual federal income taxes.</p>
			</div>
			<div class="solar-info-card">
				<div class="solar-card-icon">
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" style="width:24px;height:24px;color:var(--solar-primary);margin:0 auto;"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5h16.5m-16.5 3h16.5M3.75 10.5h16.5m-16.5 3h16.5M3.75 16.5h16.5" /></svg>
				</div>
				<h3>Net Metering Credits</h3>
				<p>Sell excess solar electricity generated by your roof back to the main power grid for utility bill credits.</p>
			</div>
			<div class="solar-info-card">
				<div class="solar-card-icon">
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" style="width:24px;height:24px;color:var(--solar-primary);margin:0 auto;"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" /></svg>
				</div>
				<h3>Increased Home Equity</h3>
				<p>Solar installations increase property resale value without increasing your local property taxes in most jurisdictions.</p>
			</div>
		</div>
	</div>
</main>

<?php
get_footer();
